id: P97A07812
initial_creation_type: input
source_metadata:
  title: Gesar Series
  language: de
  description: 'A series of texts dedicated to the legendary warrior king Gesar (ge
    sar):'
  volume:
    2cea3f56fa25410bb6fe15829c33b486:
      title: Concerning Offering Rites to the Great Lion Gesar
      parent: Commentaries
    433eefc9f3a74ceba27047e25f179673:
      title: 'The Swift Infusion of Blessings: A Guru Yoga of the Great Embodiment
        of Unchanging Awareness Wisdom'
      parent: Guru Yoga
    01cc88d6198e4d93985dacc91008ffb2:
      title: Brief Gesar Windhorse Invocation
      parent: Lungta
    969148124bd343e6b171c215468c32aa:
      title: Short Windhorse Prayer to Gesar
      parent: Lungta
    f7b32868dc7741db8238f2d345851c1e:
      title: The Swift Accomplishment of Enlightened Activity through Invocation and
        Offering
      parent: Offering Rites
    87df0deced5d4ababf9e006237d0f514:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Prayers
    05b5a04d5cd04024b73d25b3173bd0be:
      title: Brief Offering Prayer to Gesar
      parent: Prayers
    509ea3fe8835419f90bb73226cf16d59:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prayers
    70f725b559e241218dfee3d1315a1b8c:
      title: Prayer to Gesar
      parent: Prayers
    4884fac351674618be511ab5f250157d:
      title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
        Accomplishes Activities
      parent: Prayers
    a899fe92f3f94c0aafdf1dcdde3ca945:
      title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King
        of the Dralas'
      parent: Prayers
    0304588d0f47455c9dbeac7e8e66431a:
      title: 'The Swift Fulfilment of Wishes: A Brief Offering Prayer to King Gesar'
      parent: Prayers
    f4491e073e614b1ab42e53037cf13dd0:
      title: Brief Smoke Offering to the Great Lion of the World
      parent: Sang Offering
created_at: '2022-03-01T03:43:17.452718'
last_modified_at: '2022-03-01T03:43:17.452720'
